---
# tasks file for ansible-role-template

# https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html

# Step 1: Set max map count for Wazuh
- name: Set max map count for Wazuh
  sysctl:
    name: vm.max_map_count
    value: 262144

# step 2 - Clone the github repository

- name: Clone the Wazuh repository
  ansible.builtin.git:
    repo: https://github.com/wazuh/wazuh-docker.git
    dest: /opt/wazuh-docker
    version: main

# Step 4: Start the Wazuh single-node stack in detached mode
- name: Start the Wazuh single-node stack
  community.docker.docker_compose_v2:
    project_src: /opt/wazuh-docker/single-node
    state: present

