---
- name: Deploy a simple web server
  hosts: webserver
  become: true
  gather_facts: true

  roles:
    - web-server  # Provision out a web server.
    - wazuh-agent # send the Wazuh agent to the server
    
  tasks:
    - name: Provide debug output containing server address and port
      debug:
        msg: "Web server is running at {{ ansible_host }}:80"
