---
# Use `ansible-galaxy install -r requrirements.yml`
# to install these roles and collections 
roles:
  - name: geerlingguy.docker
    version: "8.0.0"
collections:
  - name: community.docker
    version: "4.2.0"
  - name: ansible.posix
    version: "1.5.0"